<?php

namespace AppBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use AppBundle\AppBundle;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use AppBundle\Entity\Products;
use AppBundle\Form\ProductsType;
use Symfony\Component\Stopwatch\Stopwatch;
use Doctrine\ORM\EntityRepository;;
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function search()
    {

        $qb=$this->createQueryBuilder('p')
                 ->select('p')
                 ->where('p.name= :name')
                 ->setParameter('name', $this);
        return $qb->getQuery()
                  ->getResult();


           /* $qb = $this->getRepository(Products::class)->createQueryBuilder('a');
            $searches = explode('',$name);

            foreach ($searches as $sk => $sv)
            {
                $cqb[]=$qb->expr()->like("CONCAT($sv, '')", "'%$sv%'");
            }
            $qb->andWhere(call_user_func_array(array($qb->expr(),"orx"),$cqb));

            $products = $qb->getResult();
            */


    }
}
