app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# app/config/routing.yml
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

login:
  path: /login
  defaults: {_controller: AppBundle:Security:login}

homepage:
 path: /homepage
 defaults: {_controller: AppBundle:Default:index}

php:
    resource: "@AppBundle/Controller/"
    type:     annotation